Pullup ticket #5612 - requested by taca lang/php71: security update
Revisions pulled up:
- lang/php71/Makefile                                           1.13
- lang/php71/Makefile.common                                    1.2
- lang/php71/distinfo                                           1.28-1.29
- lang/php/phpversion.mk                                        patch

-------------------------------------------------------------------
   Module Name:	pkgsrc
   Committed By:	taca
   Date:		Sun Oct  1 15:50:06 UTC 2017

   Modified Files:
   	pkgsrc/lang/php: phpversion.mk
   	pkgsrc/lang/php71: distinfo

   Log Message:
   lang/php71: update to 7.1.10

   28 Sep 2017, PHP 7.1.10

   - Core:
     . Fixed bug #75042 (run-tests.php issues with EXTENSION block). (John Boehr)

   - BCMath:
     . Fixed bug #44995 (bcpowmod() fails if scale != 0). (cmb)
     . Fixed bug #46781 (BC math handles minus zero incorrectly). (cmb)
     . Fixed bug #54598 (bcpowmod() may return 1 if modulus is 1). (okano1220, cmb)
     . Fixed bug #75178 (bcpowmod() misbehaves for non-integer base or modulus). (cmb)

   - CLI server:
     . Fixed bug #70470 (Built-in server truncates headers spanning over TCP
       packets). (bouk)

   - CURL:
     . Fixed bug #75093 (OpenSSL support not detected). (Remi)

   - GD:
     . Fixed bug #75124 (gdImageGrayScale() may produce colors). (cmb)
     . Fixed bug #75139 (libgd/gd_interpolation.c:1786: suspicious if ?). (cmb)

   - Gettext:
     . Fixed bug #73730 (textdomain(null) throws in strict mode). (cmb)

   - Intl:
     . Fixed bug #75090 (IntlGregorianCalendar doesn't have constants from parent
       class). (tpunt)
     . Fixed bug #75193 (segfault in collator_convert_object_to_string). (Remi)

   - PDO_OCI:
     . Fixed bug #74631 (PDO_PCO with PHP-FPM: OCI environment initialized
       before PHP-FPM sets it up). (Ingmar Runge)

   - SPL:
     . Fixed bug #75155 (AppendIterator::append() is broken when appending another
       AppendIterator). (Nikita)
     . Fixed bug #75173 (incorrect behavior of AppendIterator::append in foreach loop).
       (jhdxr)

   - Standard:
     . Fixed bug #75152 (signed integer overflow in parse_iv). (Laruence)
     . Fixed bug #75097 (gethostname fails if your host name is 64 chars long). (Andrea)


   To generate a diff of this commit:
   cvs rdiff -u -r1.27 -r1.28 pkgsrc/lang/php71/distinfo

-------------------------------------------------------------------
   Module Name:	pkgsrc
   Committed By:	jdolecek
   Date:		Mon Oct  9 21:43:30 UTC 2017

   Modified Files:
   	pkgsrc/lang/php71: Makefile.common

   Log Message:
   seems we actually don't need the EXTRACT_USING=gtar, apparently
   it's been carried over from php 5.x times


   To generate a diff of this commit:
   cvs rdiff -u -r1.1 -r1.2 pkgsrc/lang/php71/Makefile.common

-------------------------------------------------------------------
   Module Name:	pkgsrc
   Committed By:	taca
   Date:		Fri Oct 27 08:47:49 UTC 2017

   Modified Files:
   	pkgsrc/lang/php: phpversion.mk
   	pkgsrc/lang/php71: Makefile distinfo

   Log Message:
   lang/php71: Update to 7.1.11

   * pkgsrc change: remove post-extract which is not required any more.
   * including securiy fixes.

   26 Oct 2017, PHP 7.1.11

   - Core:
     . Fixed bug #75241 (Null pointer dereference in zend_mm_alloc_small()).
       (Laruence)
     . Fixed bug #75236 (infinite loop when printing an error-message). (Andrea)
     . Fixed bug #75252 (Incorrect token formatting on two parse errors in one
       request). (Nikita)
     . Fixed bug #75220 (Segfault when calling is_callable on parent).
       (andrewnester)
     . Fixed bug #75290 (debug info of Closures of internal functions contain
       garbage argument names). (Andrea)

   - Date:
     . Fixed bug #75055 (Out-Of-Bounds Read in timelib_meridian()). (Derick)

   - Apache2Handler:
     . Fixed bug #75311 (error: 'zend_hash_key' has no member named 'arKey' in
       apache2handler). (mcarbonneaux)

   - Hash:
     . Fixed bug #75303 (sha3 hangs on bigendian). (Remi)

   - Intl:
     . Fixed bug #75318 (The parameter of UConverter::getAliases() is not
       optional). (cmb)

   - litespeed:
     . Fixed bug #75248 (Binary directory doesn't get created when building
       only litespeed SAPI). (petk)
     . Fixed bug #75251 (Missing program prefix and suffix). (petk)

   - mcrypt:
     . Fixed bug #72535 (arcfour encryption stream filter crashes php). (Leigh)

   - MySQLi:
     . Fixed bug #75018 (Data corruption when reading fields of bit type). (Anatol)

   - OCI8:
     . Fixed incorrect reference counting. (Dmitry, Tianfang Yang)

   - Opcache
     . Fixed bug #75255 (Request hangs and not finish). (Dmitry)

   - PCRE:
     . Fixed bug #75207 (applied upstream patch for CVE-2016-1283). (Anatol)

   - PDO_mysql:
     . Fixed bug #75177 (Type 'bit' is fetched as unexpected string). (Anatol)

   - SPL:
     . Fixed bug #73629 (SplDoublyLinkedList::setIteratorMode masks intern flags).
       (J. Jeising, cmb)


   To generate a diff of this commit:
   cvs rdiff -u -r1.12 -r1.13 pkgsrc/lang/php71/Makefile
   cvs rdiff -u -r1.28 -r1.29 pkgsrc/lang/php71/distinfo