Pullup ticket #5611 - requested by taca lang/php70: security update
Revisions pulled up:
- lang/php70/Makefile                                           1.10
- lang/php70/distinfo                                           1.38-1.39
- lang/php/phpversion.mk                                        patch

-------------------------------------------------------------------
   Module Name:	pkgsrc
   Committed By:	taca
   Date:		Sun Oct  1 15:48:17 UTC 2017

   Modified Files:
   	pkgsrc/lang/php: phpversion.mk
   	pkgsrc/lang/php70: distinfo

   Log Message:
   lang/php70: update to 7.0.24.

   28 Sep 2017 PHP 7.0.24

   - Core:
     . Fixed bug #75042 (run-tests.php issues with EXTENSION block). (John Boehr)

   - BCMath:
     . Fixed bug #44995 (bcpowmod() fails if scale != 0). (cmb)
     . Fixed bug #46781 (BC math handles minus zero incorrectly). (cmb)
     . Fixed bug #54598 (bcpowmod() may return 1 if modulus is 1). (okano1220, cmb)
     . Fixed bug #75178 (bcpowmod() misbehaves for non-integer base or modulus). (cmb)

   - CLI server:
     . Fixed bug #70470 (Built-in server truncates headers spanning over TCP
       packets). (bouk)

   - CURL:
     . Fixed bug #75093 (OpenSSL support not detected). (Remi)

   - GD:
     . Fixed bug #75124 (gdImageGrayScale() may produce colors). (cmb)
     . Fixed bug #75139 (libgd/gd_interpolation.c:1786: suspicious if ?). (cmb)

   - Gettext:
     . Fixed bug #73730 (textdomain(null) throws in strict mode). (cmb)

   - Intl:
     . Fixed bug #75090 (IntlGregorianCalendar doesn't have constants from parent
       class). (tpunt)
     . Fixed bug #75193 (segfault in collator_convert_object_to_string). (Remi)

   - PDO_OCI:
     . Fixed bug #74631 (PDO_PCO with PHP-FPM: OCI environment initialized
       before PHP-FPM sets it up). (Ingmar Runge)

   - SPL:
     . Fixed bug #75173 (incorrect behavior of AppendIterator::append in foreach loop).
       (jhdxr)

   - Standard:
     . Fixed bug #75097 (gethostname fails if your host name is 64 chars long). (Andrea)


   To generate a diff of this commit:
   cvs rdiff -u -r1.37 -r1.38 pkgsrc/lang/php70/distinfo

-------------------------------------------------------------------
   Module Name:	pkgsrc
   Committed By:	taca
   Date:		Fri Oct 27 08:46:49 UTC 2017

   Modified Files:
   	pkgsrc/lang/php: phpversion.mk
   	pkgsrc/lang/php70: Makefile distinfo

   Log Message:
   lang/php70: Update to 7.0.25

   * pkgsrc change: remove post-extract which is not required any more.
   * including securiy fixes.

   26 Oct 2017 PHP 7.0.25

   - Core:
     . Fixed bug #75241 (Null pointer dereference in zend_mm_alloc_small()).
       (Laruence)
     . Fixed bug #75236 (infinite loop when printing an error-message). (Andrea)
     . Fixed bug #75252 (Incorrect token formatting on two parse errors in one
       request). (Nikita)
     . Fixed bug #75220 (Segfault when calling is_callable on parent).
       (andrewnester)
     . Fixed bug #75290 (debug info of Closures of internal functions contain
       garbage argument names). (Andrea)

   - Apache2Handler:
     . Fixed bug #75311 (error: 'zend_hash_key' has no member named 'arKey' in
       apache2handler). (mcarbonneaux)

   - Date:
     . Fixed bug #75055 (Out-Of-Bounds Read in timelib_meridian()). (Derick)

   - Intl:
     . Fixed bug #75318 (The parameter of UConverter::getAliases() is not
       optional). (cmb)

   - mcrypt:
     . Fixed bug #72535 (arcfour encryption stream filter crashes php). (Leigh)

   - OCI8:
     . Fixed incorrect reference counting. (Dmitry, Tianfang Yang)

   - PCRE:
     . Fixed bug #75207 (applied upstream patch for CVE-2016-1283). (Anatol)

   - litespeed:
     . Fixed bug #75248 (Binary directory doesn't get created when building
       only litespeed SAPI). (petk)
     . Fixed bug #75251 (Missing program prefix and suffix). (petk)

   - SPL:
     . Fixed bug #73629 (SplDoublyLinkedList::setIteratorMode masks intern flags).
       (J. Jeising, cmb)


   To generate a diff of this commit:
   cvs rdiff -u -r1.9 -r1.10 pkgsrc/lang/php70/Makefile
   cvs rdiff -u -r1.38 -r1.39 pkgsrc/lang/php70/distinfo